"""Synthesized metronome click sounds and the .sfz that maps them to the two
fixed notes the metronome triggers (see engine/metronome.py).

Clicks are generated on first use with plain stdlib (`wave` + `math`, no
extra dependency) as a short decaying tone - not an attempt at faithfully
emulating a real wood block/cowbell/etc., just distinct, clearly-percussive
blips per style. Accent (beat 1 of the bar) is a higher-pitched, louder
variant of the same style so the downbeat is audible against the others.
"""
from __future__ import annotations

import math
import struct
import wave
from pathlib import Path

ACCENT_NOTE = 125
NORMAL_NOTE = 126

SAMPLE_RATE = 44100
CLICK_DURATION_S = 0.06

GENERATED_DIR = Path(__file__).parent.parent / "generated" / "metronome"

# label + base frequency (Hz) for the style's normal hit; the accent hit
# reuses the same style at a higher pitch and louder amplitude.
STYLES: dict[str, dict] = {
    "digital": {"label": "Digital", "freq": 1000.0, "decay": 22.0},
    "beep": {"label": "Beep", "freq": 1400.0, "decay": 10.0},
    "wood": {"label": "Madeira", "freq": 500.0, "decay": 30.0},
    "click": {"label": "Click seco", "freq": 2400.0, "decay": 45.0},
}
DEFAULT_STYLE = "digital"


def list_styles() -> list[dict]:
    return [{"style": key, "label": v["label"]} for key, v in STYLES.items()]


def _synth_click(path: Path, freq: float, decay: float, amplitude: float) -> None:
    """Writes a short sine burst with an exponential decay envelope - a
    percussive "tick" rather than a sustained tone."""
    n_samples = int(SAMPLE_RATE * CLICK_DURATION_S)
    frames = bytearray()
    for i in range(n_samples):
        t = i / SAMPLE_RATE
        envelope = math.exp(-decay * t)
        value = amplitude * envelope * math.sin(2 * math.pi * freq * t)
        frames += struct.pack("<h", int(max(-1.0, min(1.0, value)) * 32767))

    with wave.open(str(path), "wb") as wav:
        wav.setnchannels(1)
        wav.setsampwidth(2)
        wav.setframerate(SAMPLE_RATE)
        wav.writeframes(bytes(frames))


def ensure_style_files(style: str) -> tuple[Path, Path]:
    """Returns (accent_path, normal_path) for the style, generating them on
    disk the first time this style is used."""
    meta = STYLES.get(style, STYLES[DEFAULT_STYLE])
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    accent_path = GENERATED_DIR / f"{style}_accent.wav"
    normal_path = GENERATED_DIR / f"{style}_normal.wav"
    if not accent_path.exists():
        _synth_click(accent_path, meta["freq"] * 1.5, meta["decay"], amplitude=0.9)
    if not normal_path.exists():
        _synth_click(normal_path, meta["freq"], meta["decay"], amplitude=0.6)
    return accent_path, normal_path


def write_metronome_sfz(style: str) -> Path:
    accent_path, normal_path = ensure_style_files(style)
    content = (
        "// Auto-generated by DiakoPad - metronome click, do not edit by hand\n"
        "<global> loop_mode=one_shot\n"
        f"<region> sample={accent_path.resolve()} key={ACCENT_NOTE} pitch_keycenter={ACCENT_NOTE}\n"
        f"<region> sample={normal_path.resolve()} key={NORMAL_NOTE} pitch_keycenter={NORMAL_NOTE}\n"
    )
    path = GENERATED_DIR / "metronome.sfz"
    path.write_text(content)
    return path
