"""Generates the DiakoPad drum kit .sfz files (A/B swap for forced reload).

Two files are kept side by side (diakopad_a.sfz / diakopad_b.sfz) inside the
Sfizz preset bank folder. Every time a pad is reassigned, the FULL 16-pad
mapping is written to whichever file is NOT the currently active preset, and
a MIDI Program Change selects it — forcing Zynthian's Sfizz engine to do a
real preset switch and reload the file, instead of relying on undocumented
cache/reload behaviour for a same-index reload.
"""
from __future__ import annotations

import json
from pathlib import Path

# Overridable via environment/config for the real deployment. Zynthian's
# Sfizz engine (zynthian_engine_sfizz.py) only scans banks under
# "<my_data_dir>/soundfonts/sfz/<bank>" (NOT "presets/sfizz/..." - that path
# looked plausible but the engine's root_bank_dirs don't include it), so the
# DiakoPad bank must live there to show up as a preset bank in Zynthian.
SFZ_BANK_DIR = Path(
    __import__("os").environ.get(
        "DIAKOPAD_SFZ_BANK_DIR",
        Path(__file__).parent / "sfz_bank",
    )
)
SAMPLES_DIR = Path(__file__).parent / "samples"

STATE_FILE = SFZ_BANK_DIR / "active.json"

SFZ_A = "diakopad_a.sfz"
SFZ_B = "diakopad_b.sfz"


def _read_active() -> str:
    if STATE_FILE.exists():
        try:
            data = json.loads(STATE_FILE.read_text())
            if data.get("active") in (SFZ_A, SFZ_B):
                return data["active"]
        except (json.JSONDecodeError, OSError):
            pass
    return SFZ_B  # so the first write targets A


def _write_active(name: str) -> None:
    STATE_FILE.write_text(json.dumps({"active": name}))


def _render_sfz(pads: list[dict]) -> str:
    lines = [
        "// Auto-generated by DiakoPad - do not edit by hand\n",
        # amp_veltrack=0: play at full volume regardless of hit velocity.
        # Pad controllers/velocity curves vary a lot, and "quiet unless you
        # hit it hard" was reported as a real usability problem. Per-pad
        # volume/pan/tone are set below (Volumes/Efeitos tabs).
        "<global> amp_veltrack=0\n",
    ]
    for pad in pads:
        if not pad.get("filename"):
            continue
        sample_path = (SAMPLES_DIR / pad["filename"]).resolve()
        note = pad["midi_note"]
        opcodes = [
            f"sample={sample_path}",
            f"key={note}",
            f"pitch_keycenter={note}",
            f"volume={pad.get('volume_db', 6)}",
            f"pan={pad.get('pan', 0)}",
        ]
        if pad.get("cutoff_hz"):
            opcodes += [f"cutoff={pad['cutoff_hz']:.0f}", "fil_type=lpf_2p"]
        lines.append(f"<region> {' '.join(opcodes)}\n")
    return "".join(lines)


def write_next_kit(pads: list[dict]) -> tuple[str, int]:
    """Writes the current pad mapping to the inactive slot.

    Returns (filename_written, preset_index) where preset_index is the
    Program Change value to send (0 = A, 1 = B) — assumes the two files were
    registered in that order as presets of the DiakoPad bank in Zynthian.
    """
    SFZ_BANK_DIR.mkdir(parents=True, exist_ok=True)
    active = _read_active()
    target = SFZ_A if active == SFZ_B else SFZ_B
    content = _render_sfz(pads)
    (SFZ_BANK_DIR / target).write_text(content)
    _write_active(target)
    return target, (0 if target == SFZ_A else 1)
