"""Generates each pad's own tiny .sfz file.

Now that DiakoPad runs one sfizz instance per pad (see backend/engine/), a
pad's sound can simply be reloaded by respawning that one instance - no more
A/B file alternation + Program Change trick, which only existed to force
Zynthian's own shared Sfizz engine to do a real preset reload.
"""
from __future__ import annotations

from pathlib import Path

# Overridable via environment/config for the real deployment.
SFZ_BANK_DIR = Path(
    __import__("os").environ.get(
        "DIAKOPAD_SFZ_BANK_DIR",
        Path(__file__).parent / "sfz_bank",
    )
)
SAMPLES_DIR = Path(__file__).parent / "samples"


def render_pad_sfz(pad: dict, settings: dict) -> str:
    global_opcodes = [
        # velocity_sensitive=0 (default): every hit plays at the pad's set
        # volume regardless of how hard it's struck - "quiet unless you hit
        # it hard" was reported as a real usability problem.
        f"amp_veltrack={100 if settings.get('velocity_sensitive') == '1' else 0}"
    ]
    if settings.get("sustain_mode", "1") == "1":
        # Ignore note-off entirely; the sample always plays to completion
        # once triggered, however briefly the pad is held.
        global_opcodes.append("loop_mode=one_shot")
    else:
        # Let note-off govern playback: release the pad and it stops
        # promptly (short release instead of ringing out or clicking).
        global_opcodes.append("ampeg_release=0.05")
    lines = [
        "// Auto-generated by DiakoPad - do not edit by hand\n",
        f"<global> {' '.join(global_opcodes)}\n",
    ]
    if pad.get("filename"):
        sample_path = (SAMPLES_DIR / pad["filename"]).resolve()
        note = pad["midi_note"]
        opcodes = [
            f"sample={sample_path}",
            f"key={note}",
            f"pitch_keycenter={note}",
            f"volume={pad.get('volume_db', 6)}",
            f"pan={pad.get('pan', 0)}",
        ]
        if pad.get("cutoff_hz"):
            opcodes += [f"cutoff={pad['cutoff_hz']:.0f}", "fil_type=lpf_2p"]
        lines.append(f"<region> {' '.join(opcodes)}\n")
    return "".join(lines)


def write_pad_kit(pad_number: int, pad: dict, settings: dict) -> Path:
    """Writes this pad's own .sfz and returns its path."""
    SFZ_BANK_DIR.mkdir(parents=True, exist_ok=True)
    path = SFZ_BANK_DIR / f"pad{pad_number:02d}.sfz"
    path.write_text(render_pad_sfz(pad, settings))
    return path


# Kit-browse preview notes live above any real pad note (default layout is
# 36..51) on a fixed, kit-independent range, so re-pointing the dedicated
# preview sfizz instance at a new candidate kit never has to know what MIDI
# notes the physical pads are actually configured to.
PREVIEW_NOTE_BASE = 90


def render_preview_sfz(kit: dict) -> str:
    lines = ["// Auto-generated by DiakoPad - do not edit by hand\n"]
    for pad in kit.get("pads", []):
        if not pad.get("filename"):
            continue
        sample_path = (SAMPLES_DIR / pad["filename"]).resolve()
        note = PREVIEW_NOTE_BASE + pad["pad_number"] - 1
        opcodes = [
            f"sample={sample_path}",
            f"key={note}",
            f"pitch_keycenter={note}",
            "loop_mode=one_shot",
        ]
        lines.append(f"<region> {' '.join(opcodes)}\n")
    return "".join(lines)


def write_preview_kit(kit: dict) -> Path:
    """Writes the kit-browse preview instance's .sfz (one region per
    populated pad in `kit`, see storage.get_kit) and returns its path."""
    SFZ_BANK_DIR.mkdir(parents=True, exist_ok=True)
    path = SFZ_BANK_DIR / "preview.sfz"
    path.write_text(render_preview_sfz(kit))
    return path
