"""Generates the DiakoPad drum kit .sfz files (A/B swap for forced reload).

Two files are kept side by side (diakopad_a.sfz / diakopad_b.sfz) inside the
Sfizz preset bank folder. Every time a pad is reassigned, the FULL 16-pad
mapping is written to whichever file is NOT the currently active preset, and
a MIDI Program Change selects it — forcing Zynthian's Sfizz engine to do a
real preset switch and reload the file, instead of relying on undocumented
cache/reload behaviour for a same-index reload.
"""
from __future__ import annotations

import json
from pathlib import Path

# Overridable via environment/config for the real deployment; defaults match
# a fresh install of the Sfizz "DiakoPad" bank under the Zynthian user's
# presets directory (see deploy/install.sh).
SFZ_BANK_DIR = Path(
    __import__("os").environ.get(
        "DIAKOPAD_SFZ_BANK_DIR",
        Path(__file__).parent / "sfz_bank",
    )
)
SAMPLES_DIR = Path(__file__).parent / "samples"

STATE_FILE = SFZ_BANK_DIR / "active.json"

SFZ_A = "diakopad_a.sfz"
SFZ_B = "diakopad_b.sfz"


def _read_active() -> str:
    if STATE_FILE.exists():
        try:
            data = json.loads(STATE_FILE.read_text())
            if data.get("active") in (SFZ_A, SFZ_B):
                return data["active"]
        except (json.JSONDecodeError, OSError):
            pass
    return SFZ_B  # so the first write targets A


def _write_active(name: str) -> None:
    STATE_FILE.write_text(json.dumps({"active": name}))


def _render_sfz(pads: list[dict]) -> str:
    lines = ["// Auto-generated by DiakoPad - do not edit by hand\n"]
    for pad in pads:
        if not pad.get("filename"):
            continue
        sample_path = (SAMPLES_DIR / pad["filename"]).resolve()
        note = pad["midi_note"]
        lines.append(
            f'<region> sample={sample_path} key={note} pitch_keycenter={note}\n'
        )
    return "".join(lines)


def write_next_kit(pads: list[dict]) -> tuple[str, int]:
    """Writes the current pad mapping to the inactive slot.

    Returns (filename_written, preset_index) where preset_index is the
    Program Change value to send (0 = A, 1 = B) — assumes the two files were
    registered in that order as presets of the DiakoPad bank in Zynthian.
    """
    SFZ_BANK_DIR.mkdir(parents=True, exist_ok=True)
    active = _read_active()
    target = SFZ_A if active == SFZ_B else SFZ_B
    content = _render_sfz(pads)
    (SFZ_BANK_DIR / target).write_text(content)
    _write_active(target)
    return target, (0 if target == SFZ_A else 1)
